"""remove protien sugar daily values

Revision ID: 60790c3b8f60
Revises: 69029c692190
Create Date: 2022-04-17 17:21:17.021104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60790c3b8f60'
down_revision = '69029c692190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_label', 'protein_dv')
    op.drop_column('nutrition_label', 'total_sugars_dv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_label', sa.Column('total_sugars_dv', sa.VARCHAR(length=32), nullable=True))
    op.add_column('nutrition_label', sa.Column('protein_dv', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
