"""add item labels

Revision ID: b52547573925
Revises: 60790c3b8f60
Create Date: 2022-04-17 19:22:55.503714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52547573925'
down_revision = '60790c3b8f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_labels',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dining_menu_item.item_id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.label_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_labels')
    # ### end Alembic commands ###
